language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"

install:
   - pip install -r requirements.txt --use-mirrors

before_script:
    - python web2py.py --nogui --debug=0 &
    - sleep 2 # give the webserver time to startup

script: nosetests tests/

notifications:
  irc:
    channels: "chat.freenode.net#otol"
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
