language: python
python:
    - "3.2"
    - "3.3"
    - "pypy"

install:
   - pip install -r requirements.txt --use-mirrors

script: nosetests

notifications:
  irc:
    channels: "chat.freenode.net#otol"
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
