language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"

install:
   - pip install -r requirements.txt --use-mirrors

before_script:
    - cd web2py; python web2py.py --nogui --debug=0 --port 9999 &
    - cd ..
    - sleep 2 # give the webserver time to startup

script: nosetests tests/

notifications:
  irc:
    channels: "chat.freenode.net#otol"
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
env:
    - export OTOL_API_PORT=9999

services:
    - redis-server
